'''
final implementation of the smartwatch ECG interpretation pipeline using medgemma

files:

pipline input:
Exported ECG pdf from smartwatch, form

Pipeline output: interpreted ECG

pipeline:
read inputs from form
parse pdf
process inputs
craft prompt
hit model
postprocess
display
'''

import gradio as gr
from ecg_tools import extract_ecg_strip_from_pdf, extract_text_from_pdf
import json
import numpy as np
try:
    import torch
except Exception:
    torch = None
import time
import os
import uuid
from medgemma_infer import infer_local
import medgemma_infer
from agent_schema import validate_model_output, requery_with_schema, ECG_OUTPUT_SCHEMA
from ecg_agent import ECGAgent

def post_process_promt(prompt:str):
    disclaimer = (
        "**Disclaimer: Responses generated by artificial intelligence may no be accurate.\n" \
        "This tool is intended for informational use and to satisfy individual curiousity and not to provide medical advice. "
        "Please consult with a medical professional for medical advice.** \n \n"

        "***** If you are experiencing unexplained chest pain, go to the EMERGENCY ROOM or call 911! *****\n\n"
    )

    processed_prompt = disclaimer+prompt

    return processed_prompt


def show_inputs(age: int, sex: str, diagnoses: dict, symptoms: dict, uploaded_file: str, debug: bool = False):
    os.makedirs("Logs", exist_ok=True)
    file_name = None
    if uploaded_file is not None:
        if hasattr(uploaded_file, "name"):
            file_name = uploaded_file.name
        elif isinstance(uploaded_file, dict):
            file_name = uploaded_file.get("name")

    # get inputs
    result = {
        "age": age,
        "sex": sex,
        "diagnoses": diagnoses,
        "symptoms": symptoms,
        "file_name": file_name
    }
    with open("Logs/pipeline_log_input_echo.json", "w") as file:
        json.dump(result, file)

    def _serialize(o):
        try:
            # torch tensors
            if torch is not None and isinstance(o, torch.Tensor):
                return o.cpu().tolist()
            # numpy arrays
            if isinstance(o, (np.ndarray,)):
                return o.tolist()
            # pydantic models
            if hasattr(o, "model_dump"):
                return o.model_dump()
            # objects with tolist
            if hasattr(o, "tolist"):
                try:
                    return o.tolist()
                except Exception:
                    pass
        except Exception:
            pass
        return str(o)

    # default outputs in case of failure
    image_out = None
    display_text = ""
    raw_text = ""

    try:
        # pdf data extraction
        start = time.perf_counter()
        # image extraction
        print(f"Input image filename: {file_name}")
        image, image_file, ecg_meta = extract_ecg_strip_from_pdf(file_name, verify=True, min_confidence=0.5)
        print(f"extraced image filename: {image_file}")
        if ecg_meta is None or ecg_meta.get("ecg_confidence", 0.0) < 0.5:
            # Friendly warning path: surface helpful message and metadata to the UI
            conf = ecg_meta.get("ecg_confidence") if ecg_meta else None
            warning_text = (
                f"Warning: No ECG strip confidently detected in the uploaded PDF (confidence={conf if conf is not None else 'N/A'}). "
                "Please confirm you uploaded an ECG PDF or try a clearer scan. You may also proceed anyway."
            )
            print(warning_text)
            # show the extracted image so user can inspect it, surface a warning and metadata,
            # and make the "Proceed Anyway" button visible (sixth output)
            return (
                gr.update(value=image, visible=True),
                gr.update(value={"warning": warning_text, "ecg_meta": ecg_meta}, visible=True),
                gr.update(value="", visible=False),
                gr.update(value=warning_text, visible=True),
                gr.update(value=ecg_meta or {}, visible=True),
                gr.update(visible=True),
            )

        # text extraction
        pdf_text = extract_text_from_pdf(file_name)
        elapsed = time.perf_counter() - start
        pdf_log = {
            "extracted_text": pdf_text,
            "latency": elapsed,
        }
        pdf_log.update(ecg_meta)
        with open("Logs/pipeline_log_pdf_processing.json", "w") as file:
            json.dump(pdf_log, file)

        # Delegate orchestration to ECGAgent
        agent = ECGAgent(infer_fn=infer_local)
        image_out, out_json, raw_text, cleaned_text, agent_log = agent.run(
            age=age,
            sex=sex,
            diagnoses=diagnoses,
            symptoms=symptoms,
            image_path=image_file,
            image=image,
            pdf_text=pdf_text,
            file_name=file_name,
        )

        # write agent logs
        with open("Logs/agent_logs.json", "w") as file:
            json.dump(agent_log, file, default=_serialize)

        response = post_process_promt(cleaned_text)
        # return agent log as a JSON-serializable object for gr.JSON
        try:
            agent_log_serializable = json.dumps(agent_log, default=_serialize)
        except Exception:
            agent_log_serializable = {"error": "could not serialize agent_log"}

        try:
            out_json_serializable = json.dumps(out_json, default=_serialize)
        except Exception:
            out_json_serializable = {"error": "Did not produce a viable JSON output"}

        # In debug mode, show raw output, cleaned text and agent log; otherwise show processed output and image
        if debug:
            return (
                gr.update(value=image_out, visible=True), #img
                gr.update(value=out_json_serializable, visible=True), #json
                gr.update(value=raw_text, visible=True), #raw text
                gr.update(value=response, visible=True), #plain text response
                gr.update(value=agent_log_serializable, visible=True), #log json
                gr.update(visible=False),
            )
        else:
            return (
                gr.update(value=image_out, visible=True), 
                gr.update(value=out_json_serializable, visible=True),
                gr.update(value="", visible=False),
                gr.update(value=response, visible=True),
                gr.update(value={}, visible=False),
                gr.update(visible=False),
            )

    except Exception as e:
        # log the exception and ensure Gradio receives three outputs
        err_msg = f"Pipeline error: {e}"
        try:
            with open("Logs/agent_error.json", "w") as f:
                json.dump({"error": str(e)}, f, default=_serialize)
        except Exception:
            pass
        # return empty/hidden outputs on error
        return (
            gr.update(value=None, visible=False),
            gr.update(value={"error": str(e)}, visible=True),
            gr.update(value=err_msg, visible=False),
            gr.update(value=err_msg, visible=False),
            gr.update({"error": str(e)}, visible=False),
            gr.update(visible=False),
        )


def proceed_anyway(age: int, sex: str, diagnoses: dict, symptoms: dict, uploaded_file: str, debug: bool = False):
    """Run the pipeline regardless of ECG detection confidence (triggered by user)."""
    os.makedirs("Logs", exist_ok=True)
    file_name = None
    if uploaded_file is not None:
        if hasattr(uploaded_file, "name"):
            file_name = uploaded_file.name
        elif isinstance(uploaded_file, dict):
            file_name = uploaded_file.get("name")

    try:
        # re-extract without verification to get the image and image path
        image, image_file = extract_ecg_strip_from_pdf(file_name, verify=False)

        # text extraction
        pdf_text = extract_text_from_pdf(file_name)

        agent = ECGAgent(infer_fn=infer_local)
        image_out, out_json, raw_text, cleaned_text, agent_log = agent.run(
            age=age,
            sex=sex,
            diagnoses=diagnoses,
            symptoms=symptoms,
            image_path=image_file,
            image=image,
            pdf_text=pdf_text,
            file_name=file_name,
        )

        def _serialize(o):
            try:
                if torch is not None and isinstance(o, torch.Tensor):
                    return o.cpu().tolist()
                if isinstance(o, (np.ndarray,)):
                    return o.tolist()
                if hasattr(o, "model_dump"):
                    return o.model_dump()
                if hasattr(o, "tolist"):
                    try:
                        return o.tolist()
                    except Exception:
                        pass
            except Exception:
                pass
            return str(o)

        with open("Logs/agent_logs.json", "w") as file:
            json.dump(agent_log, file, default=_serialize)

        response = post_process_promt(cleaned_text)

        try:
            agent_log_serializable = json.dumps(agent_log, default=_serialize)
        except Exception:
            agent_log_serializable = {"error": "could not serialize agent_log"}

        try:
            out_json_serializable = json.dumps(out_json, default=_serialize)
        except Exception:
            out_json_serializable = {"error": "Did not produce a viable JSON output"}

        if debug:
            return (
                gr.update(value=image_out, visible=True),
                gr.update(value=out_json_serializable, visible=True),
                gr.update(value=raw_text, visible=True),
                gr.update(value=response, visible=True),
                gr.update(value=agent_log_serializable, visible=True),
                gr.update(visible=False),
            )
        else:
            return (
                gr.update(value=image_out, visible=True),
                gr.update(value=out_json_serializable, visible=True),
                gr.update(value="", visible=False),
                gr.update(value=response, visible=True),
                gr.update(value={}, visible=False),
                gr.update(visible=False),
            )

    except Exception as e:
        err_msg = f"Pipeline error (proceed anyway): {e}"
        try:
            with open("Logs/agent_error.json", "w") as f:
                json.dump({"error": str(e)}, f)
        except Exception:
            pass
        return (
            gr.update(value=None, visible=False),
            gr.update(value={"error": str(e)}, visible=True),
            gr.update(value=err_msg, visible=False),
            gr.update(value=err_msg, visible=False),
            gr.update({"error": str(e)}, visible=False),
            gr.update(visible=False),
        )


def build_demo():
    # diagnoses = {}
    # symptoms = {}
    with gr.Blocks() as demo:
        gr.Markdown("## ECG Interpreter Input")
        with gr.Row():
            with gr.Column():
                age = gr.Number(label="Age", precision=0)
                sex = gr.Radio(['Male', 'Female'], label="Sex")
                possible_diagnoses = ['heart attack','Atrial Fibrilation','Heart Failure','Blood Clot (Stroke, PE, DVT, etc.)']
                diagnoses = gr.CheckboxGroup(choices=possible_diagnoses,label='Medical History',info='Mark any of the following diagnoses you have had')
                possible_symptoms = ["Chest Pain", "Dizziness", "Lighteaded", "Palpatations"]
                symptoms = gr.CheckboxGroup(choices=possible_symptoms, label='Symptoms', info='Mark any symptoms you were feeling at the time the EDG was taken')
                file_in = gr.File(label="Upload a file", file_types=[".pdf"])
                debug = gr.Checkbox(label="Debug mode", value=False, info='Show raw model output and agent logs')
                btn = gr.Button("Submit")
                proceed_btn = gr.Button("Proceed Anyway", visible=False)
            with gr.Column():
                gr.Markdown("## ECG Interpreter Output")
                out_clean = gr.Text(label="Model Response", visible=True)
                out_json = gr.JSON(label="Model JSON Output")
                out_raw = gr.Text(label="Raw Model Output", visible=False)
                out_img = gr.Image(label="Image preview")
                out_log_json = gr.JSON(label="Agent Log", visible=False)
            btn.click(fn=show_inputs, inputs=[age, sex, diagnoses, symptoms, file_in, debug], outputs=[out_img, out_json, out_raw, out_clean, out_log_json, proceed_btn])
            proceed_btn.click(fn=proceed_anyway, inputs=[age, sex, diagnoses, symptoms, file_in, debug], outputs=[out_img, out_json, out_raw, out_clean, out_log_json, proceed_btn])
    return demo


if __name__ == "__main__":
    # Preload the model into memory to avoid first-request latency
    try:
        medgemma_infer._load_model_once()
    except Exception:
        # if preload fails, continue and let lazy loading occur on first request
        pass

    demo = build_demo()
    demo.launch(share=True)
